### ISSUE TITLE
How to update rendering upon geometry color/material change?

### ISSUE THREAD

**Issue by aparajit-pratap** [helix-toolkit/helix-toolkit#1270]
How does one update rendering upon geometry color/material change? In an older version of Helix, we used to detach and re-attach the `GeometryModel3D` objects like so: https://github.com/DynamoDS/Dynamo/blob/f0337bd5bd86d5c75571bd7d7d6f45caa4301580/src/DynamoCoreWpf/ViewModels/Watch3D/AttachedProperties.cs#L40. 
```
var geom = (GeometryModel3D)obj;
                
                if (geom.IsAttached)
                {
                    var host = geom.RenderHost;
                    geom.Detach();
                    geom.Attach(host);
                }
```
I understand that this was probably not the best way to do it performance-wise but any suggestion on the recommended way to do so in the newer versions of Helix would be helpful. @holance?

**Comment by holance** [comment]
You don't need to do anything if you change material.
For vertex color, you can either assign a new vertex color array to geometry3D and it will be updated automatically. 

Or change single color in existing array and manually call `Geometry3D.UpdateColors()` to notify a change.

**Comment by aparajit-pratap** [comment]
@holance thanks for your response. I did try some of the approaches in the samples but didn't have any luck. 

I'm actually maintaining a list of `Element3D` objects in the scene in the viewmodel and then binding to this property in the view.xaml  (similar to this [sample ](https://github.com/helix-toolkit/helix-toolkit/blob/4f4eb85c7f304013f28a52ba8df5b7023241857a/Source/Examples/WPF.SharpDX/MaterialDemo/MainWindow.xaml#L60), where `Model1` is actually my list). I believe this list needs to be an `ObservableElement3DCollection`, for it to work, am I right? However, that didn't work either, as I don't think changing one or more properties of elements (like `Colors`) in this collection will trigger an update unless we add or remove from this list, would it? 

On the other hand, I cannot really bind to individual `MeshGeometry3D` objects in the scene either (as in the dynamo texture demo) as my scene is dynamically changing and I only want to change the color of a few of these objects interactively in real-time.

Given this background, would you be able to suggest another approach?

**Comment by holance** [comment]
Which helixtoolkit version are you using?

**Comment by aparajit-pratap** [comment]
> Which helixtoolkit version are you using?

2.9.0

**Comment by holance** [comment]
If you change Geometry3D.Colors, you need to call `Geometry3D.UpdateColors()` and it will update automatically. Of cause, you have to use VertColorMaterial for mesh to use per vertex coloring.

**Comment by holance** [comment]
I think your problem may be duplicated with #1247, which has been fixed. Please try again.

**Comment by mjkkirschner** [comment]
@holance thanks for your help here - I have mostly got this working - one issue remains for me, but it's not related to color updates - instead I am wondering about using vertex colors along with phong lighting - (normal/light direction (non specular) based lighting would also be acceptable).

Does the `vertColorMaterial` included in Helix.wpf.Sharpdx have support for what I am describing? Is it something that can be added or I can add? Any hints how to go about it?

Also a related question - do the phongMaterials have a maximum number of supported directional lights?

**Comment by holance** [comment]
Do you have to use vertex color? Or could you  use texture coordinate with color strip texture for color sampling?

Currently the max light support is 8.

**Comment by mjkkirschner** [comment]
Vertex colors would be ideal (I think), as there will be many meshes created dynamically and it seems to use textures I would need to create different materials for each mesh and different texture maps on the fly from the vertex colors - we support an API where users pass us meshes with vertex colors only.

**Comment by holance** [comment]
So you want to use vertex color as diffuse color in Phong material, right?

**Comment by mjkkirschner** [comment]
@holance vertex color as the diffuse color in a Phong Material - exactly! I won't turn down blending with the diffuseColor 😉  - but I don't think it is required for my use case.

**Comment by holance** [comment]
Now you can use `VertexColorBlendingFactor = 1` to use vertex color in phong material.
