### ISSUE TITLE
SharpDX GetBestAdapter method will not always get (The Best) one for .NET 4.5

### ISSUE THREAD

**Issue by cokemal** [helix-toolkit/helix-toolkit#282]
After updating from Win7 to Win10, I had got white screen issues. None of the provided solutions worked for me including [#224](https://github.com/helix-toolkit/helix-toolkit/issues/224). I tried to figure out what was the exact reason for my issue. After debugging sessions, I found that GetBestAdapter method will not always bring me the "The Best" one. Because  systemMemory and videoMemory variables are not calculated correctly when I use .NET 4.5 version of the SharpDX branch. I realized this after running .NET 4.0 samples (in which memory variables are calculated correctly.) Below you can see the screenshots from debugging session. 

.NET 4.0 
![screenshot_40](https://cloud.githubusercontent.com/assets/16599593/15252831/5b8120b0-1938-11e6-8c35-246440f58bf1.PNG)

.NET 4.5
![screenshot](https://cloud.githubusercontent.com/assets/16599593/15252842/6561186a-1938-11e6-967d-bad249eb7ece.PNG)

I solved this issue by changing the best adapter condition like this.

`if ((bestAdapter == null) || (videoMemory > bestVideoMemory) && (systemMemory >bestSystemMemory))
{
                        bestAdapter = item;
                        bestAdapterIndex = adapterIndex;
                        bestVideoMemory = videoMemory;
                        bestSystemMemory = systemMemory;
}`

For your information.

**Comment by JeremyAnsel** [comment]
This was fixed in #164 and #508.

**Comment by holance** [comment]
Fixed

**Comment by juyanith** [comment]
For what it is worth I am still having this issue (10/25/2017). I have a laptop with an Nvidia and multi-monitor setup. 

Changing line 135 in Effects.cs to:

`if ((bestAdapter == null) || (videoMemory > bestVideoMemory) && (systemMemory > bestSystemMemory))`

solves the problem.

**Comment by holance** [comment]
@juyanith Could you provide your adapter description details from f.Adapters?

**Comment by juyanith** [comment]
![image](https://user-images.githubusercontent.com/10644546/32052018-7e95890c-ba1c-11e7-983e-1ce9ee5f0e98.png)

I traced though the code and the original check causes the Nvidia adapter to be chosen while the changed code causes the Intel adapter to be chosen. I would have thought the Nvidia to be the "best" choice so I'm surprised something about it is causing an issue. Maybe this is a driver issue?

**Comment by JeremyAnsel** [comment]
With this code:
```csharp
if ((bestAdapter == null)
    || (videoMemory > bestVideoMemory) && (systemMemory > bestSystemMemory))
```
the Intel adapter is chosen (first adapter).

With this code:
```csharp
if ((bestAdapter == null)
    || (videoMemory > bestVideoMemory)
    || ((videoMemory == bestVideoMemory) && (systemMemory > bestSystemMemory)))
```
the NVIDIA adapter is chosen (best video memory).

**Comment by Squall-Leonhart** [comment]
The logic in this conditional might actually be breaking multiple dedicated gpu systems that have 3+ displays spread across the cards, but i have no way to properly test it myself.

https://github.com/TexTools/FFXIV_TexTools_UI/issues/56
https://github.com/TexTools/FFXIV_TexTools_UI/issues/222

the nvidia gpu at index1 may be chosen due to having little video memory used instead of the nvidia gpu at index0, the former not being the DWM attached gpu at any time.

**Comment by holance** [comment]
> The logic in this conditional might actually be breaking multiple dedicated gpu systems that have 3+ displays spread across the cards, but i have no way to properly test it myself.
> 
> [TexTools/FFXIV_TexTools_UI#56](https://github.com/TexTools/FFXIV_TexTools_UI/issues/56) [TexTools/FFXIV_TexTools_UI#222](https://github.com/TexTools/FFXIV_TexTools_UI/issues/222)
> 
> the nvidia gpu at index1 may be chosen due to having little video memory used instead of the nvidia gpu at index0, the former not being the DWM attached gpu at any time.

User can pass in their own adapterIndex during EffectsManager creation if they have such a complex graphics card configuration. I don't believe our developers have such gpu configuration to validate it either.

**Comment by Squall-Leonhart** [comment]
Revisiting this, it might be better to make use of EnumAdapterByGpuPreference instead of doing a resource check, this way you'll always get the device in control of the swapchain instead of relying on a resource test that relies on race condition-ish behavior,

**Comment by holance** [comment]
> Revisiting this, it might be better to make use of EnumAdapterByGpuPreference instead of doing a resource check, this way you'll always get the device in control of the swapchain instead of relying on a resource test that relies on race condition-ish behavior,

It is not available in SharpDX(not actively maintained anymore). You can create our own code to get the index and pass into effectsmanager constructor.

**Comment by Squall-Leonhart** [comment]
> The logic in this conditional might actually be breaking multiple dedicated gpu systems that have 3+ displays spread across the cards, but i have no way to properly test it myself.
> 
> [TexTools/FFXIV_TexTools_UI#56](https://github.com/TexTools/FFXIV_TexTools_UI/issues/56) [TexTools/FFXIV_TexTools_UI#222](https://github.com/TexTools/FFXIV_TexTools_UI/issues/222)
> 
> the nvidia gpu at index1 may be chosen due to having little video memory used instead of the nvidia gpu at index0, the former not being the DWM attached gpu at any time.

Confirming that as written, this method causes issues in the cited scenario, and modern muxless igp/dgpu laptops where an external display lives on the dgpu.

<img width="1932" height="1005" alt="Image" src="https://github.com/user-attachments/assets/c2e9de68-28c9-407c-afd3-e1cea98c917c" />
